apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: default
spec:
    secretName: nginx-tls-secret
    privateKey:
      rotationPolicy: Always
    issuerRef:
        name: nginx-clusterissuer
        kind: ClusterIssuer
    dnsNames:
    - "www.mongo-express.com"