version: "2.4"
services:
  neo4j:
    labels:
      - "integration"
    networks:
      - "tests"
    image: neo4j:4.0
    volumes:
      - neo4j-data:/data
      - neo4j-plugins:/plugins
      - neo4j-import:/import
    ports:
      - "7474"
      - "7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/test
    restart: unless-stopped

networks:
  tests:
    name: "tests"

volumes:
  neo4j-data:
  neo4j-plugins:
  neo4j-import: